project:
  type: website

website:
  title: "Práctica de DSP"
  sidebar:
    - title: "Ejercicios"
      style: "docked"
      contents:
        - section: "Librerias"
          contents:
            - notebooks/librerias/librerias.qmd
        - section: "Ejercicio 1"
          contents:
            - notebooks/ejercicio1/01_x_input.qmd
            - notebooks/ejercicio1/02_h_system.qmd
            - notebooks/ejercicio1/03_h_systems_num.qmd
            - notebooks/ejercicio1/04_y_output.qmd
            - notebooks/ejercicio1/data/
        - section: "Ejercicio 2"
          contents:
            - notebooks/ejercicio2/01_h_system.qmd
            - notebooks/ejercicio2/data/
  navbar:
    left:
      - href: index.qmd
        text: "Inicio"
      - text: "Ejercicio 1"
        menu:
          - text: "Señal de Entrada"
            href: notebooks/ejercicio1/01_x_input.qmd
          - text: "Respuesta Impulsional"
            href: notebooks/ejercicio1/02_h_system.qmd
          - text: "Análisis Numérico"
            href: notebooks/ejercicio1/03_h_systems_num.qmd
          - text: "Salida del Sistema"
            href: notebooks/ejercicio1/04_y_output.qmd
      - text: "Ejercicio 2"
        menu:
          - text: "Respuesta Impulsional"
            href: notebooks/ejercicio2/01_h_system.qmd
format:
  html:
    theme: flatly
    toc: true
execute:
  freeze: auto
